### ISSUE TITLE
Migrate kubernetes.dev to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by chalin** [kubernetes/contributor-site#354]
This issue is part of a CNCF-wide effort to upgrade project websites to GA4 since **Google has deprecated Universal Analytics** (UA). For more details, see:

- https://github.com/cncf/techdocs/issues/108, including reference to a suggested [migration process](https://github.com/cncf/techdocs/blob/main/docs/analytics.md#migrating-to-google-analytics-4), which we've used to [migrate a few CNCF projects](https://docs.google.com/spreadsheets/d/1Mx4LhdI2Un-rvGMI73SlHxQH9D2HABAJclMB3dd6lnA) already.

### Tasks

- [x] Configure GA4 ID `G-JPP6RFM2BP` through [Netlify snippet injection], "Google Analytics 4 - only in production", just before `</head>`:
  ```liquid
  {% if CONTEXT == 'production' %}
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-JPP6RFM2BP"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
  
    gtag('config', 'G-JPP6RFM2BP');
  </script>
  {% endif %}
  ```
- [x] Confirm that the GA4 site tag is receiving events
- [x] Confirm that the UA site tag is still receiving events

### Notes

- Corresponding issue for main site: https://github.com/kubernetes/website/issues/35299
- Followup: #355

### Pre-migration website analytics info

- UA ID: `UA-98841695-5` ([analytics console](https://analytics.google.com/analytics/web/#/report-home/a98841695w242826908p226287827))
- Website is build with very old versions of Hugo and Docsy

/cc @caniszczyk @nate-double-u @a-mccarthy

[Netlify snippet injection]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/

**Comment by chalin** [comment]
@jimangel @onlydole et al.: can one of you either grant me access to this website's Netlify account or add the [Netlify snippet] shown in the opening comment? Thanks!

[Netlify snippet]: https://docs.netlify.com/site-deploys/post-processing/snippet-injection/

**Comment by chalin** [comment]
Pinging all concerned parties, including @onlydole who had offered to look into this. It's been two months since this issue was created. There has been discussion of granting someone in the CNCF access to Netlify. If that happens shortly, then I'll be able to make the change myself.

**Comment by chalin** [comment]
Just chatted with @onlydole out-of-band. Within the next two weeks we'll do a pair-configuring session to complete the tasks for this issue.

**Comment by chalin** [comment]
Scratch that, @onlydole doesn't have access to the kubernetes.dev Netlify account.

**Comment by mrbobbytables** [comment]
I can add you and any others - we should move it under the rest of the managed org, I don't remember why it was created separately initially

**Comment by nate-double-u** [comment]
@divya-mohan0209 is working on cleaning up/adding the Netlify users list

https://github.com/kubernetes/website/discussions/38019, https://github.com/kubernetes/website/issues/38839

**Comment by divya-mohan0209** [comment]
Hey @nate-double-u , thank you for flagging this. 

@mrbobbytables and @chalin if these requests can wait another week, we aim to have the consensus period for everything listed on the issue by Feb 8th. I could add @nate-double-u & @chalin myself once done and also open a k/community PR for listing whoever has owner/collaborator access for future records. Again, I don't want to block any work so if the access is blocking work that has time-based constraints I am absolutely okay with you giving them access.

**Comment by chalin** [comment]
> I can add you and any others - we should move it under the rest of the managed org, I don't remember why it was created separately initially

@mrbobbytables I'll take you up on your offer to grant access. It turns out that @divya-mohan0209 is not authorized to do so (as communicated out-of-band on 02/22).

**Comment by mrbobbytables** [comment]
@chalin whats your email? I'll add you to the team (can dm it to me in k8s or cncf slack if you don't want it here in github) 👍

**Comment by chalin** [comment]
Done!
