### ISSUE TITLE
Tracking Issue KCSEU 2024

### ISSUE THREAD

**Issue by mfahlandt** [kubernetes/contributor-site#464]
ToDo's for the KCSEU 2024 related to the website

- [x] Create scaffold page for summit #461 
- [x] Insert CfP #463 
- [x] Insert Notes Folder #463 
- [x] Insert Location & Venue Details #466 
- [x] Insert Registration Link & Details #471 
- [x] Remove Cfp #474 
- [x] Insert Sched #478 
- [x] Insert Uncof Details & Issue #474 
- [x] Insert Contributor Social Details #479

**Comment by kumarankit999** [comment]
Hey @mfahlandt I would like to add the  Insert Location Venue Details, Registration Link & Details.

**Comment by mfahlandt** [comment]
> Hey @mfahlandt I would like to add the Insert Location Venue Details, Registration Link & Details.

Hey Ankit, unfortunate it is really hard to distribute any of those tasks here as we basically do it in an ad-hoc way as information arrive. 
There are plenty of topics that evolve around content in [sig-docs](https://github.com/kubernetes/website) maybe you have a look there. They are also always looking for help

**Comment by mfahlandt** [comment]
@natalisucks please check & confirm - i think we are finished here

**Comment by natalisucks** [comment]
/close
This is completed! Thanks @mfahlandt and team 🎉
