### ISSUE TITLE
Tracking Issue KCSNA 2024

### ISSUE THREAD

**Issue by mfahlandt** [kubernetes/contributor-site#506]
ToDo's for the KCSNA 2024 related to the website

- [x] Create scaffold page for summit 
- [x] Insert CfP 
- [x] Insert Notes Folder 
- [x] Insert Location & Venue Details  
- [x] Insert Registration Link & Details  
- [x] Remove Cfp 
- [x] Insert Sched 
- [x] Insert Uncof Details & Issue  
- [x] Insert Contributor Social Details

**Comment by jberkus** [comment]
kcsna is complete

/close
